language: scala
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential
  - mkdir protobuf_install
  - pushd protobuf_install
  - wget http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz
  - tar xzf protobuf-2.5.0.tar.gz
  - cd  protobuf-2.5.0
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - protoc --version
  - popd
  - pwd
  - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - wget -nv http://archive.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz
  - tar zxf thrift-0.9.2.tar.gz
  - cd thrift-0.9.2
  - chmod +x ./configure
  - ./configure --disable-gen-erl --disable-gen-hs --without-ruby --without-haskell --without-erlang
  - sudo make install
  - cd ..

scala:
  - 2.11.8
